{
  parserClass="com.github.peco2282.mcdatapack.language.parser.McFunctionParser"
  parserUtilClass="com.intellij.lang.parser.GeneratedParserUtilBase"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="McFunction"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.peco2282.mcdatapack.language.psi"
  psiImplPackage="com.github.peco2282.mcdatapack.language.psi.impl"

  elementTypeHolderClass="com.github.peco2282.mcdatapack.language.psi.McFunctionTypes"
  elementTypeClass="com.github.peco2282.mcdatapack.language.psi.McFunctionElementType"
  tokenTypeClass="com.github.peco2282.mcdatapack.language.psi.McFunctionTokenType"

  tokens = [
    COMMENT_TOKEN         = "regexp:#.*"
    CRLF_TOKEN            = "regexp:\R"
    SPACE_TOKEN           = "regexp:[ \t\f]+"
    STRING_TOKEN          = "regexp:\"([^\"\\]|\\.)*\"|'([^'\\]|\\.)*'"

    // Major Commands: 1.21.1
    ADVANCEMENT_TOKEN     = "advancement"
    ATTRIBUTE_TOKEN       = "attribute"
    EXECUTE_TOKEN         = "execute"
    BOSSBAR_TOKEN         = "bossbar"
    CLEAR_TOKEN           = "clear"
    CLONE_TOKEN           = "clone"
    DAMAGE_TOKEN          = "damage"
    DATA_TOKEN            = "data"
    DATAPACK_TOKEN        = "datapack"
    DEBUG_TOKEN           = "debug"
    DEFAULTGAMEMODE_TOKEN = "defaultgamemode"
    DIFFICULTY_TOKEN      = "difficulty"
    EFFECT_TOKEN          = "effect"
    ENCHANT_TOKEN         = "enchant"
    EXPERIENCE_TOKEN      = "experience"
    FILL_TOKEN            = "fill"
    FILLBIOME_TOKEN       = "fillbiome"
    FORCELOAD_TOKEN       = "forceload"
    FUNCTION_TOKEN        = "function"
    GAMEMODE_TOKEN        = "gamemode"
    GAMERULE_TOKEN        = "gamerule"
    GIVE_TOKEN            = "give"
    HELP_TOKEN            = "help"
    ITEM_TOKEN            = "item"
    JFR_TOKEN             = "jfr"
    KICK_TOKEN            = "kick"
    KILL_TOKEN            = "kill"
    LIST_TOKEN            = "list"
    LOCATE_TOKEN          = "locate"
    LOOT_TOKEN            = "loot"
    ME_TOKEN              = "me"
    MSG_TOKEN             = "msg"
    PARTICLE_TOKEN        = "particle"
    PERF_TOKEN            = "perf"
    PLACE_TOKEN           = "place"
    PLAYSOUND_TOKEN       = "playsound"
    RECIPE_TOKEN          = "recipe"
    RETURN_TOKEN          = "return"
    RIDE_TOKEN            = "ride"
    SAY_TOKEN             = "say"
    SCHEDULE_TOKEN        = "schedule"
    SCOREBOARD_TOKEN      = "scoreboard"
    SETBLOCK_TOKEN        = "setblock"
    SETIDLETIMEOUT_TOKEN  = "setidletimeout"
    SETWORLDSPAWN_TOKEN   = "setworldspawn"
    SPAWNPOINT_TOKEN      = "spawnpoint"
    SPECTATE_TOKEN        = "spectate"
    SPREADPLAYERS_TOKEN   = "spreadplayers"
    STOPSOUND_TOKEN       = "stopsound"
    SUMMON_TOKEN          = "summon"
    TAG_TOKEN             = "tag"
    TEAM_TOKEN            = "team"
    TEAMMSG_TOKEN         = "teammsg"
    TELEPORT_TOKEN        = "teleport"
    TELL_TOKEN            = "tell"
    TELLRAW_TOKEN         = "tellraw"
    TICK_TOKEN            = "tick"
    TIME_TOKEN            = "time"
    TITLE_TOKEN           = "title"
    TM_TOKEN              = "tm"
    TP_TOKEN              = "tp"
    TRIGGER_TOKEN         = "trigger"
    WEATHER_TOKEN         = "weather"
    WHITELIST_TOKEN       = "whitelist"
    WORLDBORDER_TOKEN     = "worldborder"
    XP_TOKEN              = "xp"

    // Subcommands & Keywords
    IF_TOKEN              = "if"
    UNLESS_TOKEN          = "unless"
    RUN_TOKEN             = "run"
    ONLY_TOKEN            = "only"
    ENTITY_TOKEN          = "entity"
    MODIFY_TOKEN          = "modify"
    STORAGE_TOKEN         = "storage"
    SET_TOKEN             = "set"
    FROM_TOKEN            = "from"
    ADD_TOKEN             = "add"
    PLAYERS_TOKEN         = "players"
    ACTIONBAR_TOKEN       = "actionbar"
    MATCHES_TOKEN         = "matches"
    AS_TOKEN              = "as"
    AT_TOKEN              = "at"
    ANCHORED_TOKEN        = "anchored"
    FACING_TOKEN          = "facing"
    BLOCK_TOKEN           = "block"
    ITEMS_TOKEN           = "items"
    STORE_TOKEN           = "store"
    RESULT_TOKEN          = "result"
    SCORE_TOKEN           = "score"
    TEXT_TOKEN            = "text"
    VALUE_TOKEN           = "value"
    EYES_TOKEN            = "eyes"
    REVOKE_TOKEN          = "revoke"
    GRANT_TOKEN           = "grant"
    GET_TOKEN             = "get"
    MERGE_TOKEN           = "merge"
    REMOVE_TOKEN          = "remove"
    ENABLE_TOKEN          = "enable"
    DISABLE_TOKEN         = "disable"
    BASE_TOKEN            = "base"
    MODIFIER_TOKEN        = "modifier"
    QUERY_TOKEN           = "query"
    TAKE_TOKEN            = "take"
    OBJECTIVES_TOKEN      = "objectives"
    SETDISPLAY_TOKEN      = "setdisplay"
    EMPTY_TOKEN           = "empty"
    JOIN_TOKEN            = "join"
    LEAVE_TOKEN           = "leave"
    RATE_TOKEN            = "rate"
    FREEZE_TOKEN          = "freeze"
    STEP_TOKEN            = "step"
    STOP_TOKEN            = "stop"
    UNFREEZE_TOKEN        = "unfreeze"
    SUBTITLE_TOKEN        = "subtitle"
    TIMES_TOKEN           = "times"
    CENTER_TOKEN          = "center"
    WARNING_TOKEN         = "warning"
    MASTER_TOKEN          = "master"
    MUSIC_TOKEN           = "music"


    // Layer 3: Target Selectors
    SELECTOR_S            = "@s"
    SELECTOR_A            = "@a"
    SELECTOR_P            = "@p"
    SELECTOR_E            = "@e"
    SELECTOR_R            = "@r"

    // Layer 4: Structural symbols
    CONTINUATION_TOKEN    = "regexp:\\\\(\r\n|\r|\n)"
    MACRO_TOKEN           = "regexp:\$[a-zA-Z_][a-zA-Z0-9_]*"
    DOT_TOKEN             = "."
    GTE_TOKEN             = ">="
    LTE_TOKEN             = "<="
    GT_TOKEN              = ">"
    LT_TOKEN              = "<"
    DOTDOT_TOKEN          = ".."

    LBRACK                = "["
    RBRACK                = "]"
    LBRACE                = "{"
    RBRACE                = "}"
    COLON                 = ":"
    COMMA                 = ","

    COMMAND_TOKEN         = "regexp:[a-z_][a-z0-9_]*"
    ARGUMENT_TOKEN        = "regexp:[^ \n\r\t\f#\"'\[\]{},]+"
  ]
}

mcFunctionFile ::= item*
private item ::= (command_line | COMMENT_TOKEN | CRLF_TOKEN | SPACE_TOKEN | CONTINUATION_TOKEN)

// コマンド行：execute コマンドか、それ以外の汎用コマンド
command_line ::= execute_command | generic_command {pin=1}

// execute コマンド：modifier を並べ、run の後に新しいコマンドを再帰的にパース
private execute_command ::= EXECUTE_TOKEN (SPACE_TOKEN | CONTINUATION_TOKEN execute_modifier_line | execute_modifier)* (SPACE_TOKEN RUN_TOKEN SPACE_TOKEN command_line)? {pin=1}
private execute_modifier_line ::= SPACE_TOKEN? execute_modifier (SPACE_TOKEN execute_modifier)*

// execute 以外の汎用コマンド：先頭単語を COMMAND として認識し、残りを argument でキャッチ
private generic_command ::= command (SPACE_TOKEN | CONTINUATION_TOKEN SPACE_TOKEN? | (json | argument))* {pin=1}

// 行頭のコマンド名
command ::= ADVANCEMENT_TOKEN | ATTRIBUTE_TOKEN | EXECUTE_TOKEN | BOSSBAR_TOKEN | CLEAR_TOKEN | CLONE_TOKEN | DAMAGE_TOKEN
  | DATA_TOKEN | DATAPACK_TOKEN | DEBUG_TOKEN | DEFAULTGAMEMODE_TOKEN | DIFFICULTY_TOKEN | EFFECT_TOKEN | ENCHANT_TOKEN
  | EXPERIENCE_TOKEN | FILL_TOKEN | FILLBIOME_TOKEN | FORCELOAD_TOKEN | FUNCTION_TOKEN | GAMEMODE_TOKEN | GAMERULE_TOKEN
  | GIVE_TOKEN | HELP_TOKEN | ITEM_TOKEN | JFR_TOKEN | KICK_TOKEN | KILL_TOKEN | LIST_TOKEN | LOCATE_TOKEN | LOOT_TOKEN
  | ME_TOKEN | MSG_TOKEN | PARTICLE_TOKEN | PERF_TOKEN | PLACE_TOKEN | PLAYSOUND_TOKEN | RECIPE_TOKEN | RETURN_TOKEN
  | RIDE_TOKEN | SAY_TOKEN | SCHEDULE_TOKEN | SCOREBOARD_TOKEN | SETBLOCK_TOKEN | SETIDLETIMEOUT_TOKEN | SETWORLDSPAWN_TOKEN
  | SPAWNPOINT_TOKEN | SPECTATE_TOKEN | SPREADPLAYERS_TOKEN | STOPSOUND_TOKEN | SUMMON_TOKEN | TAG_TOKEN | TEAM_TOKEN
  | TEAMMSG_TOKEN | TELEPORT_TOKEN | TELL_TOKEN | TELLRAW_TOKEN | TICK_TOKEN | TIME_TOKEN | TITLE_TOKEN | TM_TOKEN
  | TP_TOKEN | TRIGGER_TOKEN | WEATHER_TOKEN | WHITELIST_TOKEN | WORLDBORDER_TOKEN | XP_TOKEN
  | IF_TOKEN

// execute の modifier 部分やサブコマンド等
keyword ::= RUN_TOKEN | ONLY_TOKEN | ENTITY_TOKEN | MODIFY_TOKEN | STORAGE_TOKEN | SET_TOKEN
  | FROM_TOKEN | ADD_TOKEN | PLAYERS_TOKEN | ACTIONBAR_TOKEN | MATCHES_TOKEN | AS_TOKEN | AT_TOKEN | ANCHORED_TOKEN | FACING_TOKEN | BLOCK_TOKEN
  | ITEMS_TOKEN | STORE_TOKEN | RESULT_TOKEN | SCORE_TOKEN | TEXT_TOKEN | VALUE_TOKEN | EYES_TOKEN | REVOKE_TOKEN | GRANT_TOKEN | DATA_TOKEN
  | GET_TOKEN | MERGE_TOKEN | REMOVE_TOKEN | ENABLE_TOKEN | DISABLE_TOKEN | BASE_TOKEN | MODIFIER_TOKEN
  | QUERY_TOKEN | TAKE_TOKEN | OBJECTIVES_TOKEN | SETDISPLAY_TOKEN | EMPTY_TOKEN | JOIN_TOKEN | LEAVE_TOKEN
  | RATE_TOKEN | FREEZE_TOKEN | STEP_TOKEN | STOP_TOKEN | UNFREEZE_TOKEN | SUBTITLE_TOKEN | TIMES_TOKEN
  | CENTER_TOKEN | WARNING_TOKEN | MASTER_TOKEN | MUSIC_TOKEN
  | IF_TOKEN | UNLESS_TOKEN

// execute の modifier 内：keyword か json か argument のどちらか
private execute_modifier ::= keyword | json | argument

// Generic argument
argument ::= ARGUMENT_TOKEN | COMMAND_TOKEN | STRING_TOKEN | command | keyword
  | SELECTOR_S | SELECTOR_A | SELECTOR_P | SELECTOR_E | SELECTOR_R
  | MACRO_TOKEN
  | GTE_TOKEN | LTE_TOKEN | GT_TOKEN | LT_TOKEN | DOTDOT_TOKEN | DOT_TOKEN
  | COLON | LBRACK | RBRACK | LBRACE | RBRACE | COMMA
  | CONTINUATION_TOKEN

// JSON support
json ::= json_array | json_object

json_array  ::= LBRACK (json_element (COMMA json_element)*)? RBRACK
json_object ::= LBRACE (json_property (COMMA json_property)*)? RBRACE

// json_value: argument tokens optionally followed by a json structure (e.g. key={...} or key=[...])
private json_value ::= json | (argument | STRING_TOKEN)+ json?

private json_element  ::= SPACE_TOKEN? json_value SPACE_TOKEN?
private json_property ::= SPACE_TOKEN? (argument | STRING_TOKEN) SPACE_TOKEN? COLON SPACE_TOKEN? json_value SPACE_TOKEN?
